server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态获取路由的功能，利用微服务名进行路由；
      routes:
        - id: payment_routh # payment_route #路由的id，没有固定规则但要求唯一，建议写服务名
          #uri: http://localhost:8001
          uri: lb://cloud-provider-payment # uri 以 lb:// 开头，lb 代表从注册中心获取服务
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由
        - id: payment_routh2 # payment_route #路由的id，没有固定规则但要求唯一，建议写服务名
          uri: http://localhost:8001
          predicates:
            - Path=/payment/create/**  # 断言，路径相匹配的进行路由




eureka:
  instance:
    hostname: gateway-service
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
